adobe/aio-cli-plugin-cloudmanager

src/commands/cloudmanager/start-execution.js, test/__mocks__/node-fetch.js, test/commands/start-execution.test.js
Add the output of the execution id when starting an execution
#19 
* Jest tests
* Manual running of CLI
=> output execution id. fixes #19

src/client.js, src/commands/cloudmanager/get-execution-step-log.js, src/constants.js, src/index.js, test/__mocks__/data/execution1001.json, test/__mocks__/node-fetch.js, test/commands/get-execution-step-log.test.js
Adds the get-execution-step-logs command
#16
Nice to have easy access to step logs
* unit tests
* manual testing against real pipeline
=> add support for getting execution step log. fixes #16

package-lock.json, package.json, test/__mocks__/node-fetch.js
node-fetch 8.3.0 seems to have stricter checking of duplication of routes which this project uses for testing different org id headers.
#70
See #70
Unit tests
=> fix compatibility with node-fetch 8.3.0. fixes #70

src/client.js, src/commands/cloudmanager/set-environment-variables.js, test/commands/set-environment-variables.test.js
Deleting a secretString variable requires sending the type along with the deletion request. Failure to do so results in an error.
Fixing this also has the nice side-effect of not trying to delete variables that don't exist (thus saving some API calls).
#96 
See bug report
Updated tests
=> check variable types before trying to delete. fixes #96

src/base-environment-variables-command.js, src/commands/cloudmanager/list-environment-variables.js, src/commands/cloudmanager/set-environment-variables.js
Moved the file base-environment-variables-command.js from src/commands/cloudmanager to src. This seems to be the easiest way (without moving to TypeScript) to do fix the issue.
#101 
The readme is misleading
Unit tests
- [] I have added tests to cover my changes.
=> hide base environment variables command from README. fixes #101

src/base-environment-variables-command.js, src/cloudmanager-helpers.js, src/commands/cloudmanager/delete-environment.js, src/commands/cloudmanager/download-logs.js, src/commands/cloudmanager/list-available-log-options.js, src/commands/cloudmanager/open-developer-console.js, src/commands/cloudmanager/set-environment-variables.js, src/commands/cloudmanager/tail-log.js, test/commands/list-environment-variables.test.js
(h/t @ghenzler). fixes #140
Anywhere an environment id is taken, it also accepts an e prefixed value
#140
Some minor annoyance
Unit tests
Manual testing
=> Allow to use 'e'-prefixed env ids as found in cloud manager URLs 

README.md, src/base-execution-command.js, src/base-variables-command.js, src/cloudmanager-helpers.js, src/commands/cloudmanager/get-current-execution.js, src/commands/cloudmanager/get-execution-step-details.js, src/commands/cloudmanager/get-quality-gate-results.js, src/commands/cloudmanager/list-available-log-options.js, src/commands/cloudmanager/list-current-executions.js, src/commands/cloudmanager/list-environment-variables.js, src/commands/cloudmanager/list-environments.js, src/commands/cloudmanager/list-pipeline-variables.js, src/commands/cloudmanager/list-pipelines.js, src/commands/cloudmanager/list-programs.js, src/commands/cloudmanager/set-environment-variables.js, src/commands/cloudmanager/set-pipeline-variables.js, src/common-flags.js, test/cloudmanager-helpers.test.js
Added options to allow the user to control the output format for commands which render a table. The two new options are:
```
-j, --json                   output in json
-y, --yaml                   output in yaml
```
1. Introduced a common function and flags to support user control over the output format.
2. Added options for json and yaml
3. Implemented output on commands which render a table
4. Updated README to show new options
#147 
Allow for machine consumable outputs
Introduced new tests
Ran existing tests
Manual testing on mac running catalina
=> [#147] Support for JSON and YAML output formats

src/cloudmanager-helpers.js, test/__mocks__/@adobe/aio-lib-ims.js, test/cloudmanager-helpers.test.js
remove call to context.setCurrent() -- unnecessary and can be done with passing the context name to context.get
Remove the setting of the current context
#212 
Quoting #212 
> Needs to be added to .gitignore, pollutes created content-packages, and in general creates unnecessary files on the hard disk.
* unit tests
=> fix(auth): do not create .aio file in local directory. fixes #212

src/hooks/prerun/check-ims-context-config.js, test/hooks/prerun/check-ims-context-config.test.js
When validating the IMS context configuration, if an alternate configuration is specified using a flag, use it.
#237 
The purpose of validation is to check that the configuration is proper. If an alternate configuration is specified, that configuration should be validated instead of the default.
Unit tests
=> fix(hook): validate ims context configuration from flag. fixes #237

src/hooks/prerun/check-ims-context-config.js, test/hooks/prerun/check-ims-context-config.test.js
The IMS context validation should only be done on commands from this plugin, otherwise you can't actually configure (unless you manually edit the .aio file which no one should)
TBD
Makes the plugin really hard to use
* Unit testing
=> fix(hook): only check ims context on commands for this plugin

src/cloudmanager-helpers.js, test/commands/environment/set-variables.test.js
* Change how numeric flags are parsed by ignoring JSON-parsed numbers.
This is perhaps not the most elegant way to address this, but expedient.
#253 
This is very strange behavior and would not be detectable unless the numeric value was particularly high.
* Unit test
=> fix(variables): fix how numeric values are parsed. fixes #253

package.json
fixes #256 because @adobe/aio-lib-ims-jwt 2.1.1 removes requirement for technical_account_email field
* Force version of @adobe/aio-lib-ims-jwt to 2.1.1 or higher
#256 
Manual local testing
=> fix(deps): force the use of @adobe/aio-lib-ims-jwt higher than 2.1.1

src/hooks/prerun/prerun-all.js, test/hooks/prerun/prerun-all.test.js
Correctly pass `this` to hooks from prerun hook
#295
Bug fix
Unit test
Manual testing
=> fix(hook): check-ims-config is not correctly throwing errors. fixes #295

.github/workflows/ci.yml
Add OS Matrix to build on Windows and OSX in addition to Ubuntu
=> chore(ci): add OS matrix to ci workflow

src/cloudmanager-helpers.js, src/commands/cloudmanager/environment/set-variables.js, src/constants.js, src/hooks/init/migrate-jwt-context-hook.js, src/hooks/prerun/check-ims-context-config.js, test/commands/environment/bind-ip-allowlist.test.js
Small refactoring to ensure that variables services and allowlist services are kept in sync via common constant.
Refactor service list to be common between IP Allowlist commands and environment variables.
#335
Unit tests
=> feat(ip-allowlist): support binding ip allowlists to preview. fixes #335

.github/workflows/ci.yml, README.md, package.json
Support for TLS 1.0 and 1.1 is being retired by Adobe in mid-July.
BREAKING CHANGE: Installation on Node 10 will now fail
Node 12 is now the minimal version
#372
Ensures usage of correct node version with TLS 1.2 support
CI
=> feat: require node 12 as minimum version. fixes #372

src/base-commerce-cli-command.js, src/base-commerce-command.js, src/commands/cloudmanager/commerce/bin-magento/maintenance/status.js, test/__mocks__/cli-ux.js, test/commands/commerce/bin-magento/maintenance/status.test.js
This will add the base class for all Commerce commands. The class encapsulates the logic of calling the POST endpoint to initiate the command and then poll the get endpoint while the command is running.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/383
Commerce CLI commands need to be integrated into the Cloud Manager Plugin as the Cloud Manager API will soon have commands for running CLI commands on Cloud Manager hosted Commerce programs.
I have added the simplest command maintenance:status in my development environment that extends this base class. I wrote unit tests that match the unit tests in the app. All of the unit tests pass.
=> Add Base Commerce Command

package.json
Cloud Manager does not show descriptions for the nested commerce commands
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/396
This will show descriptions for each part of the Commerce CLI commands.
Locally
=> fix(commerce): add descriptions. fixes#396

src/base-commerce-cli-command.js, test/commands/commerce/bin-magento/maintenance/status.test.js
This PR will update the methods in BaseCommerceCommand from getCLICommand and postCLICommand to getCommerceCommandExecution and postCommerceCommandExecution.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/404
Fixes the names of the methods to match what will be in the lib
Unit tests
=> feat(commerce): update method names. fixes#404

src/base-commerce-cli-command.js, test/commands/commerce/bin-magento/maintenance/status.test.js
Currently, the status that base commerce cli command will poll the GET endpoint for a command is "RUNNING" and "CREATING." The API team changed the "CREATING" status to "PENDING." The file should be updated to reflect that change.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/409
Unit tests
=> Update RUNNING status to PENDING in base-commerce-cli-comman d

src/base-commerce-cli-command.js, test/commands/commerce/bin-magento/maintenance/status.test.js
The status should be PENDING in the formatStatus method. The status is CREATING in the formatStatus method.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/411
Unit Tests
=> fix(commerce): change status to pending. fixes#411

test/commands/commerce/bin-magento/maintenance/status.test.js, test/commands/current-execution/advance.test.js, test/commands/current-execution/cancel.test.js, test/commands/current-execution/get.test.js, test/commands/environment/delete.test.js, test/commands/environment/download-logs.test.js, test/commands/environment/list-available-log-options.test.js, test/commands/environment/list-variables.test.js, test/commands/environment/open-developer-console.test.js, test/commands/environment/set-variables.test.js, test/commands/environment/tail-log.test.js, test/commands/execution/get-quality-gate-results.test.js, test/commands/execution/get-step-details.test.js, test/commands/execution/get-step-log.test.js, test/commands/execution/tail-step-log.test.js, test/commands/list-programs.test.js, test/commands/org/list.test.js, test/commands/org/select.test.js, test/commands/pipeline/create-execution.test.js, test/commands/pipeline/delete.test.js, test/commands/pipeline/list-executions.test.js, test/commands/pipeline/list-variables.test.js, test/commands/pipeline/set-variables.test.js, test/commands/pipeline/update.test.js, test/commands/program/delete.test.js, test/commands/program/list-current-executions.test.js, test/commands/program/list-environments.test.js, test/commands/program/list-pipelines.test.js
There's a bunch of usage of `toSatisfy` which isn't really necessary since `toThrow` can be used matching the message either via a string or regex
Simplify test code
Tests
=> chore(test): remove unnecessary usage of toSatisfy

src/commands/cloudmanager/commerce/get-command-execution.js, test/commands/commerce/get-command-execution.test.js
This will add a command to allow users to see the status of a single command
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/437
Users that execute a command will need to see the status of the command
Unit tests
=> feat(commerce): add get-command fixes #437

src/commands/cloudmanager/commerce/get-command-execution.js, test/commands/commerce/get-command-execution.test.js
The table in get-commerce-execution passes the object to the formatTime function in cli.table. These should be strings. Additionally, the test names the command get-command and it should be get-command-execution. Finally, one of the tests had the assertions commented out.
This PR changes the objects to strings in the formatTime function. It renames the test to match the command. It also removes the commented out assertion in the test.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/441
It fixes a few bugs in the implementation of get-commerce-execution
unit tests
=> fix(commerce): fix implementation and test for get-command-execution fixes #441

package.json, src/commands/cloudmanager/commerce/list-command-executions.js, test/commands/commerce/list-command-executions.test.js
This PR will add a command to list all executions for a given program and environment.
In addition to list commands for a given program and environment the command allows the user to use optional flags to filter by type, status and command.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/440
This solves the need for a command to list the status and details for all commerce cli command executions
Unit test
=> feat(commerce): list command executions fixes #440

src/commands/cloudmanager/commerce/bin-magento/indexer/reindex.js, src/commands/cloudmanager/commerce/bin-magento/maintenance/status.js, src/commands/cloudmanager/commerce/get-command-execution.js, src/commands/cloudmanager/commerce/list-command-executions.js, src/commands/cloudmanager/environment/bind-ip-allowlist.js, src/commands/cloudmanager/environment/delete.js, src/commands/cloudmanager/environment/download-logs.js, src/commands/cloudmanager/environment/list-available-log-options.js, src/commands/cloudmanager/environment/list-ip-allowlist-bindings.js, src/commands/cloudmanager/environment/list-variables.js, src/commands/cloudmanager/environment/open-developer-console.js, src/commands/cloudmanager/environment/set-variables.js, src/commands/cloudmanager/environment/tail-log.js, src/commands/cloudmanager/environment/unbind-ip-allowlist.js, src/commands/cloudmanager/ip-allowlist/bind.js, src/commands/cloudmanager/ip-allowlist/unbind.js, src/common-args.js
This pr will update all instances of environmentId declared as a one-off argument in commands
All of the instances of environmentId that were declared in the args object of commands are replaced by an imported environmentId arg that is located in the central commonArgs file.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/457
The above issue
Unit tests
=> fix(environmentId): make environmentId a common arg fixes #457

package.json, src/commands/cloudmanager/commerce/bin-magento/cache/clean.js, test/commands/commerce/bin-magento/cache/clean.test.js
This PR will add cache:clean to the commands available for Commerce command executions.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/460
Unit tests
=> feat(commerce): add cache:clean fixes #460

src/commands/cloudmanager/commerce/bin-magento/cache/flush.js, test/commands/commerce/bin-magento/cache/flush.test.js
This PR will add a cache:flush command execution for Commerce programs.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/462
Unit Tests
=> feat(commerce): add cache:flush fixes #462

src/commands/cloudmanager/commerce/bin-magento/maintenance/enable.js, test/commands/commerce/bin-magento/maintenance/enable.test.js
This PR will add a maintenance:enable command execution for Commerce programs.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/464
Unit Tests
=> feat(commerce): add maintenance:enable fixes #464

src/commands/cloudmanager/commerce/bin-magento/maintenance/disable.js, test/commands/commerce/bin-magento/maintenance/disable.test.js
This PR will add a maintenance:disable command execution for Commerce programs.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/466
Unit tests
=> feat(commerce): add maintenance:disable fixes #466

test/commands/commerce/bin-magento/app/config/dump.test.js, test/commands/commerce/bin-magento/app/config/import.test.js, test/commands/commerce/bin-magento/cache/clean.test.js, test/commands/commerce/bin-magento/cache/flush.test.js, test/commands/commerce/bin-magento/indexer/reindex.test.js, test/commands/commerce/bin-magento/maintenance/disable.test.js, test/commands/commerce/bin-magento/maintenance/enable.test.js, test/commands/commerce/bin-magento/maintenance/status.test.js, test/commands/pipeline/set-variables.test.js
For tests that run commands that use `this.warn` or `this.info`, the log output from jest is polluted with extraneous messages. That can be avoided by mocking these methods on the command instance.
n/a
Avoid log noise in local testing and CI.
Unit tests, of course :)
=> chore(test): clean up test output by mocking info/warn

.github/workflows/ci.yml, package.json
Updates to semantic-release weren't detected as problematic because semantic-release is not run during the PR build. Trying to check that...
=> chore(ci): add semantic-release-dry-run to ci build

package.json, src/base-commerce-cli-command.js, src/cloudmanager-helpers.js, src/commands/cloudmanager/commerce/bin-magento/app/config/dump.js, src/commands/cloudmanager/commerce/bin-magento/app/config/import.js, src/commands/cloudmanager/commerce/bin-magento/cache/clean.js, src/commands/cloudmanager/commerce/bin-magento/cache/flush.js, src/commands/cloudmanager/commerce/bin-magento/indexer/reindex.js, src/commands/cloudmanager/commerce/bin-magento/maintenance/disable.js, src/commands/cloudmanager/commerce/bin-magento/maintenance/enable.js, src/commands/cloudmanager/commerce/bin-magento/maintenance/status.js, src/common-commerce-args.js, src/common-commerce-flags.js, test/commands/commerce/bin-magento/app/config/dump.test.js, test/commands/commerce/bin-magento/app/config/import.test.js, test/commands/commerce/bin-magento/cache/clean.test.js, test/commands/commerce/bin-magento/cache/flush.test.js, test/commands/commerce/bin-magento/indexer/reindex.test.js, test/commands/commerce/bin-magento/maintenance/disable.test.js, test/commands/commerce/bin-magento/maintenance/enable.test.js, test/commands/commerce/bin-magento/maintenance/status.test.js
All relevant commerce commands can now handle the optional args and flags as defined by devdocs: https://devdocs.magento.com/guides/v2.4/reference/cli/magento.html#maintenanceenable
* cache:clean, cache:flush, and reindex can now handle their optional args
* all commerce commands can pass common commerce flags
* updated unit tests
=> feat(commerce): args fixes #489

src/hooks/prerun/help-override.js, test/hooks/prerun/help-override.test.js, test/hooks/prerun/prerun-all.test.js
Add a hook to intercept cases where `-h` is passed to commands to ensure consistent behavior
#507 
Inconsistency between strict and non-strict commands is weird -- strict isn't really something users should think about.
* Unit tests
* Manual tests
=> fix: ensure that -h works for all commands. fixes #506

src/commands/cloudmanager/commerce/bin-magento/cache/clean.js, src/commands/cloudmanager/commerce/bin-magento/cache/flush.js, src/commands/cloudmanager/commerce/bin-magento/indexer/reindex.js, test/commands/commerce/bin-magento/cache/clean.test.js, test/commands/commerce/bin-magento/cache/flush.test.js, test/commands/commerce/bin-magento/indexer/reindex.test.js
For all commerce commands that accept arguments, pass all arg array to api, instead of slicing after the first index. 
* Refactored cache:clean, cache:flush, and indexer:reindex commands
* Updated unit tests
call cache:clean, cache:flush, or indexer:reindex commands with arguments, you will see first arg is ignored
manual and unit
=> fix(commerce): args fixes #552

.github/workflows/ci.yml, .github/workflows/release.yml
The release.yml github action failed with a syntax error.
https://github.com/adobe/aio-cli-plugin-cloudmanager/runs/7695466966?check_suite_focus=true
This appear to be due to the older version (12) of node being used. Updating release node version to 16.
This also reverts the disabling of the e2e tests in the Github actions, since it just occurred to me that is why JE removed node from the ci.yml matrix.
=> Upgraded release node version to 16 (from 12)

.github/workflows/ci.yml, CHANGELOG.md, README.md, package.json, src/base-variables-command.js, src/commands/cloudmanager/environment/bind-ip-allowlist.js, src/commands/cloudmanager/environment/set-variables.js, src/commands/cloudmanager/environment/unbind-ip-allowlist.js, src/commands/cloudmanager/ip-allowlist/bind.js, src/commands/cloudmanager/ip-allowlist/unbind.js, src/commands/cloudmanager/pipeline/set-variables.js, src/common-args.js, src/constants.js, test/__mocks__/@adobe/aio-lib-cloudmanager.js, test/commands/pipeline/set-variables.test.js
Supports service for pipeline variables was added in the CLI.
#686
The pipeline variable API now supports service for pipeline variables and that should be available in the CLI.
Unit tests
=> feat(variables): support service-specific pipeline variables. fixes #686

README.md, e2e/e2e.js, package.json, src/ConfigurationErrors.js, src/hooks/prerun/check-ims-context-config.js, test/hooks/prerun/check-ims-context-config.test.js
- fixes #676 
- upgraded IMS library to 6.5.0 which supports both JWT and OAuth based on config type
- updated e2e tests to include OAuth authentication also
- added validations for OAuth config as well
=> fix(auth): add support for OAuth authentication in parallel to JWT

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, package.json
Update to the latest node version that CM CLI can support.
https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/699
Unit tests and build on CI/CD.
- [] I have added tests to cover my changes.
=> chore(node): update to the latest node version that CM CLI can support fixes 699

src/ValidationErrors.js, src/cloudmanager-helpers.js, src/commands/cloudmanager/environment/tail-log.js, test/cloudmanager-helpers.test.js, test/commands/environment/tail-log.test.js
Add retry mechanism in case of token expired error
[702](https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/702)
Tail log operation should run with no interraption
Unit tests, regression tests
=> fix(auth): tail logs refresh token #702

src/commands/cloudmanager/ip-allowlist/get-binding-details.js, test/commands/ip-allowlist/get-binding-details.test.js
While doing
`aio cloudmanager:ip-allowlist:get-binding-details ... `
an exception was present due to the fact that the 2 items compared were different types.
Fixes https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/706
It's impacting usual workflows
Locally
=> fix: ipallowlists:exception on getBindingDetails fixes #706
