adobe/aio-cli-plugin-cloudmanager

src/client.js, src/cloudmanager-helpers.js, src/commands/cloudmanager/advance-current-execution.js, src/commands/cloudmanager/cancel-current-execution.js, src/commands/cloudmanager/index.js, src/constants.js, src/index.js, test/__mocks__/data/execution1005.json, test/__mocks__/data/execution1006.json, test/__mocks__/data/execution1007.json, test/__mocks__/node-fetch.js, test/commands/advance-current-execution.test.js, test/commands/cancel-current-execution.test.js, test/commands/list-current-executions.test.js
=> introduce cancel and advance commands. fixes #7

package-lock.json, package.json
=> Greenkeeper/eslint plugin jest 22.11.1

package-lock.json, package.json
=> Greenkeeper/eslint plugin jest 22.13.5

package-lock.json, package.json
=> Greenkeeper/eslint plugin jest 22.15.1

package-lock.json, package.json, src/client.js, src/constants.js, test/__mocks__/node-fetch.js
Switch to use templated execution link
#25
Removes some hand-crafted URI generation code
Unit tests plus run against production program
- [X I have read the **CONTRIBUTING** document.
=> Use templated execution link. fixes #25

README.md, src/client.js, src/commands/cloudmanager/list-environments.js, src/constants.js, src/index.js, test/__mocks__/node-fetch.js, test/commands/list-environments.test.js
Add support for listing environments
#30
New API available with 2019.9.0
* unit tests
=> adding support for listing environments. fixes #30

package-lock.json, package.json, src/commands/cloudmanager/get-execution-step-details.js, src/index.js, test/commands/get-execution-step-details.test.js
Adds a get-execution-step-details
#32 
* Unit Tests
* Manual Tests
=> Add get execution details command. fixes #32

src/client.js, src/commands/cloudmanager/tail-log.js, src/index.js, test/commands/tail-log.test.js
Renamed (with old alias) tail-logs to tail-log
=> rename tail-logs to tail-log

README.md, src/client.js, src/commands/cloudmanager/delete-pipeline.js, src/index.js, test/__mocks__/node-fetch.js, test/commands/delete-pipeline.test.js
Adds support for delete-pipeline command
#41
* Unit tests
=> add delete-pipeline command. fixes #41

src/commands/cloudmanager/get-execution-step-details.js, src/commands/cloudmanager/index.js
* Update the examples in index.js
#44 
Examples should be up to date
=> update help output. fixes #44

README.md, src/client.js, src/commands/cloudmanager/index.js, src/commands/cloudmanager/update-pipeline.js, src/index.js, test/__mocks__/node-fetch.js, test/commands/update-pipeline.test.js
Add `update-pipeline` command
#42
* unit tests
=> add support for editing pipeline branch. fixes #42

package-lock.json, package.json
=> Greenkeeper/eslint plugin jest 23.0.2

src/commands/cloudmanager/list-available-log-options.js, test/__mocks__/cli-ux.js, test/commands/list-available-log-options.test.js
* Add specific console message when no log options
#51
* Updated unit tests
=> add better console info when no log options are availble. fixes #51

src/commands/cloudmanager/list-environments.js, test/commands/list-environments.test.js
* Replace `undefined` with `""` on description
#54 
Usability
* unit test
=> display blank for undefined environment description. fixes #54

src/commands/cloudmanager/update-pipeline.js, test/commands/update-pipeline.test.js
Add a new flag to update-pipeline to pass in a tag
#57 
Unit tests
Manual tests
=> add explicit tag flag to update-pipeline. fixes #57

package-lock.json, src/client.js, src/commands/cloudmanager/open-developer-console.js, src/index.js, test/__mocks__/cli-ux.js, test/__mocks__/node-fetch.js, test/commands/open-developer-console.test.js
Add the mentioned command
#59 
Unit Tests
Manual Testing
=> add open-developer-console command. fixes #59

package-lock.json, package.json
* move `@oclif/plugin-help` from `devDependencies` to `dependencies`
* replace `@adobe/aio-cna-core-config` with `@adobe/aio-lib-core-config`
#61
Reduces confusion on install
=> remove warnings on install. fixes #61

package-lock.json, package.json
=> Greenkeeper/cli ux 5.4.1

package-lock.json, package.json, src/client.js, src/commands/cloudmanager/base-environment-variables-command.js, src/commands/cloudmanager/list-environment-variables.js, src/commands/cloudmanager/set-environment-variables.js, src/constants.js, test/__mocks__/node-fetch.js, test/commands/list-environment-variables.test.js, test/commands/set-environment-variables.test.js
=> environment variables support. fixes #76

src/commands/cloudmanager/base-environment-variables-command.js, src/commands/cloudmanager/list-environment-variables.js, src/commands/cloudmanager/set-environment-variables.js, test/commands/set-environment-variables.test.js
Consolidate variables table output to super class
#78
To fix the bug
Manual testing
Updated unit test
=> fixing wrong output for secrets. fixes #78

test/__mocks__/node-fetch.js, test/commands/delete-pipeline.test.js, test/commands/list-environment-variables.test.js, test/commands/list-environments.test.js, test/commands/list-pipelines.test.js, test/commands/list-programs.test.js, test/commands/set-environment-variables.test.js, test/commands/start-execution.test.js
Improve test coverage for error cases
=> improve error case tests

package.json, src/client.js
Rewrite how http responses are handled:
* Centralized ok checking
* Reject promise on non ok response, logging response text
#80 
Sometimes the error response has useful information.
Manual testing
Unit tests
=> output http response body on error to debug. fixes #80

src/client.js, src/commands/cloudmanager/get-execution-step-log.js, test/__mocks__/node-fetch.js, test/commands/get-execution-step-log.test.js
* Add new flag to get-execution-step-logs
#84
Useful specifically for code quality
Unit tests
Manual tests
=> support alternate step log files. fixes #84

package-lock.json, package.json
=> Greenkeeper/fetch mock 9.1.1

.snyk, package-lock.json, package.json
Add snyk configuration
https://greenkeeper.io/
=> add snyk configuration and update runtime plugin

src/client.js, test/__mocks__/data/execution1008.json, test/__mocks__/data/execution1009.json, test/__mocks__/data/execution1010.json, test/__mocks__/node-fetch.js, test/commands/cancel-current-execution.test.js
Switch endpoint for cancelling paused deploy step.
#99 
* unit testing
- [] I have updated the documentation accordingly.
=> correct endpoint used for cancelling paused deploy step. fixes #99

src/client.js, src/constants.js, test/__mocks__/node-fetch.js, test/commands/set-environment-variables.test.js
Update error processing code to look for problem JSON responses and include validation errors.
This code could be expanded in the future to handle other problem types.
#115
=> include validation errors in error message. fixes #115

src/client.js, src/commands/cloudmanager/delete-program.js, src/index.js, test/__mocks__/node-fetch.js, test/commands/delete-program.test.js
Adds the delete-program command
#119 
* Unit test
* Actual test
=> add delete-program command. fixes #119

src/client.js, test/__mocks__/node-fetch.js, test/commands/list-programs.test.js
Handle JSON error response body
#122
Helpful to understand what went wrong
Manual testing
=> add code and message to error. fixes #122

package.json, src/client.js
Replace `debug` with `@adobe/aio-lib-core-logging` to align with Adobe standards
Local testing
=> migrate to aio-lib-core-logging

src/base-pipeline-variables-command.js, src/base-variables-command.js, src/client.js, src/commands/cloudmanager/list-pipeline-variables.js, src/commands/cloudmanager/set-pipeline-variables.js, src/index.js, test/__mocks__/node-fetch.js, test/commands/list-pipeline-variables.test.js, test/commands/set-pipeline-variables.test.js
Add new list-pipeline-variables/set-pipeline-variables commands
#131 
New feature in Cloud Manager API
* Unit tests
=> support pipeline variables. fixes #131

src/client.js, src/commands/cloudmanager/delete-environment.js, src/index.js, test/__mocks__/node-fetch.js, test/commands/cancel-current-execution.test.js, test/commands/delete-environment.test.js, test/commands/delete-pipeline.test.js, test/commands/delete-program.test.js, test/commands/get-execution-step-details.test.js, test/commands/get-execution-step-log.test.js, test/commands/get-quality-gate-results.test.js, test/commands/start-execution.test.js, test/commands/update-pipeline.test.js
* Add delete-environment command
* Update some error messages
#133
CLI for existing API
* Unit tests
=> add delete-environment command. fixes #133

src/commands/cloudmanager/download-logs.js, src/commands/cloudmanager/tail-log.js
Correct the descriptions of the `tail-log` and `download-logs` commands
#142 
Because the generated documentation and help output are wrong.
=> correct desription of tail and download log commands

package.json, src/commands/cloudmanager/start-execution.js, test/__mocks__/@adobe/aio-lib-cloudmanager.js, test/commands/start-execution.test.js
#145
- [] I have updated the documentation accordingly.
=> replace use of startExecution with createExecution. fixes #145

README.md, src/base-variables-command.js, test/__mocks__/@adobe/aio-lib-core-config.js, test/commands/environment/set-variables.test.js
Enable variables to be passed through stdin
#150
See #150 
* Unit Tests
* Manual Testing
=> feat(variables): support JSON input on stdin. fixes #150

README.md, package.json, src/base-execution-command.js, src/cloudmanager-helpers.js, src/commands/cloudmanager/execution/get-step-details.js, src/commands/cloudmanager/pipeline/list-executions.js, src/commands/cloudmanager/program/list-current-executions.js, test/commands/current-execution/get.test.js, test/commands/pipeline/list-executions.test.js
* add pipeline:list-executions command
* unify how step properties are formatted
#201 
https://github.com/adobe/aio-lib-cloudmanager/issues/60
* unit tests
=> feat: add pipeline:list-executions. fixes #201

README.md, package.json
Enable standalone execution by creating a bin script (well, the script already existed, but wasn't included in the tarball).
#219 
Manual testing
=> feat: support standalone execution. fixes #219

package.json, src/hooks/prerun/check-ims-context-config.js, src/hooks/prerun/prerun-all.js
* Ensure that hooks are processed in a guaranteed order.
* Ensure that the arguments are passed to the `parse` function in the ims check hook
#280
Bug fix
=> fix(hooks): restore behavior of default environment id. fixes #280

commitlint.config.js, package.json
* Move commitlint to configuration file to take advantage of local plugin support
* Introduce local commit plugin to verify exactly one reference per commit but ignore chore, docs, etc. issue types
#283
Ensure commits have proper issue references
=> chore(build): commitlint should verify issue references. fixes #283

test/hooks/prerun/prerun-all.test.js
=> chore(test): forgot test for prerun-all hook

src/base-environment-variables-command.js, test/__mocks__/@adobe/aio-lib-cloudmanager.js, test/commands/environment/list-variables.test.js
Add Status To List Variables Table enhancement
To show the user what the status of the variable is
The code was tested locally by calling the actual api.
=> feat(variables): show status on list variables table

src/commands/cloudmanager/environment/set-variables.js
Add another service to the array to generate the flags.
#335
New AEM feature
Manual testing
=> feat(variables): support preview as an additional service. fixes #335

README.md, package.json, src/cloudmanager-helpers.js, src/hooks/prerun/check-ims-context-config.js, test/cloudmanager-helpers.test.js, test/hooks/prerun/check-ims-context-config.test.js
Enable usage of browser-based authentication via the cli plugin once authenticated using `aio auth:login`
#346 
Enables usage of the CLI without creating a service account
* Unit Tests
* Manual Testing
=> feat(auth): enable the use of browser-based authentication. fixes #346

test/cloudmanager-helpers.test.js, test/commands/environment/list-variables.test.js
Add some tests for paths which were not tested
=> chore(test): add some missing test cases

package.json
Update topic in package.json to have proper description for ip-allowlist topic.
#397
Better help
Manual testing
=> fix(help): add proper description for ip-allowlist topic. fixes #397

package.json
Update lib version
#421
Ensures installations/update of CLI work.
Manual testing
=> fix(commerce): update minimum version of lib. fixes #421

package.json, src/commands/cloudmanager/pipeline/invalidate-cache.js, test/__mocks__/@adobe/aio-lib-cloudmanager.js, test/commands/pipeline/invalidate-cache.test.js
Add new pipeline:invalidate-cache command
#434 
New API
Unit Test
Manual test
=> feat(pipeline): add support for pipeline cache invalidation. fixes #434

src/commands/cloudmanager/commerce/bin-magento/app/config/import.js, test/commands/commerce/bin-magento/app/config/import.test.js
Added commerce command app:config:import
* added commerce command app:config:import
* added unit tests to cover these changes
* unit testing
=> feat(app:config:import): commerce fixes #473

src/common-commerce-flags.js, test/commands/commerce/bin-magento/app/config/dump.test.js, test/commands/commerce/bin-magento/app/config/import.test.js, test/commands/commerce/bin-magento/cache/clean.test.js, test/commands/commerce/bin-magento/cache/flush.test.js, test/commands/commerce/bin-magento/indexer/reindex.test.js, test/commands/commerce/bin-magento/maintenance/disable.test.js, test/commands/commerce/bin-magento/maintenance/enable.test.js, test/commands/commerce/bin-magento/maintenance/status.test.js
Added descriptions to Commerce flags
* added descriptions to commerce flags
* I snuck in some improvements to commerce command unit tests, to more thoroughly test the expected result of each test
=> Issue 499: Added descriptions to Commerce flags

README.md, package.json, src/hooks/init/load-permission-info.js, test/hooks/init/load-permission-info.test.js
Consolidated dependency update to be proxy-aware:
* Replace node-fetch with @adobe/aio-lib-core-networking
* Update @adobe/aio-lib-ims
* Update @adobe/aio-lib-cloudmanager
#177 
Resolves basic proxy support
Manual testing
Unit Tests
=> feat: add support for proxies when using aio 8.2.0. fixes #177

.github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, README.md, e2e/e2e.js
=> chore(test): set up ci for e2e and add a basic authenticated test

package.json
=> chore(deps): remove deprecated codecov module

package.json, src/commands/cloudmanager/pipeline/update.js, test/commands/pipeline/update.test.js
* Add new flags to pipeline:update
* Update aio-lib-cloudmanager
#572
New API feature
manual testing, unit test
=> feat(pipeline:update): support changing the environment id. fixes #572

src/commands/cloudmanager/environment/download-logs.js, src/commands/cloudmanager/environment/tail-log.js
* Add permission info object to these commands
#610
accuracy of permission output
Manual testing
=> fix: update permission info for environment logs commands. fixes #610

package.json, src/ValidationErrors.js, src/base-variables-command.js, test/base-variables-command.test.js, test/commands/environment/set-variables.test.js, test/data/variables.json, test/data/variables.yaml
Add new yamlStdin and yamlFile flags to the variables set commands
#615
Some people like YAML. But mostly multi-line support
Unit tests
=> feat(variables): add support for yaml variable input. fixes #615

.github/workflows/release.yml
Change the release to use ubuntu-latest (fix for 674)
release job does not run (retries due to the ubuntu dependency)
=> fix(release): update release job to ubuntu-latest Fixes: #674

README.md
- documentation changes in format
=> docs: update format for OAuth S2S

package.json
Status for approve step returned correctly now
[708](https://github.com/adobe/aio-cli-plugin-cloudmanager/issues/708)
Status for approve step was returned incorectly
Unit tests, regression tests
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.
=> fix(pipeline): corrected status for pipeline in approve step #708
